# Change these first
owner: bentleyherron # Your GitHub username
repo: uptime # Your Github repository name

assignees:
  - bentleyherron

# Add your sites here
sites:
  - name: Personal Website
    url: https://bentleyherron.com
  - name: Jeopardy Game
    url: https://jeopardy.bentleyherron.dev
  - name: Jeopardy API
    url: https://jeopardy-api.bentleyherron.dev
  - name: Jeopardy API Docs
    url: https://jeopardy-api.bentleyherron.dev
  - name: Matchga.me
    url: https://matchga.me
  - name: Matchga.me API
    url: $MATCHGAME_URL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bentleyherron.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bentley Herron Sites
  introTitle: "Status of sites run by Bentley Herron"
  introMessage: This is a status page which uses **real-time** data from my managed sites.
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
